---
title: "Introdução à linguagem R: manipulação e visualização de dados"
subtitle: Maurício Humberto Vancine, Helena Oliveira 
draft: false
event: "XXX Semana de Estudos da Ecologia"
event_url: http://www.rc.unesp.br/see/
location: Rio Claro, SP, Brazil
summary: "Introdução à linguagem R realizado na XXX Semana de Estudos da Ecologia"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2019-11-06T08:00:00Z"
date_end: "2019-11-07T12:00:00Z"
all_day: false
publishdate: "2020-03-08"

links:
- icon: link
  icon_pack: fas
  name: evento
  url: "http://www.rc.unesp.br/see/"
- icon: github
  icon_pack: fab
  name: material
  url: "https://github.com/mauriciovancine/minicurso-r-see-2019"

categories:
  - short course
tags:
  - short course
  - r
lastmod: "2019-11-05"
featured: no
image:
  caption: "[Imagem by SEE](http://www.rc.unesp.br/see/)"
  focal_point: "center"
  preview_only: no
projects: []
---

A linguagem R vem se destacando nos últimos anos (desde de 2000), como a principal ferramenta para manejo, visualização e análise de dados, principalmente na área de Ecologia, Psicologia, Economia, e mais recentemente, na Ciência de Dados. Neste curso serão abordados quatro temas introdutórios dessa linguagem: (i) introdução e funcionamento da linguagem R e do software RStudio, (ii) estrutura e manipulação de dados, (iii) introdução ao tidyverse, e (iv) visualização de dados. A carga horária será de aproximadamente 08 horas, onde será focada a parte teórico-prática, intercalada com a realização de exercícios para fixação do conteúdo. Ao final do curso, espera-se que os participantes tenham uma noção geral do funcionamento da linguagem e das potenciais aplicações dentro da área de análise de dados ecológicos.
