---
title: "Introduction to Species Distribution Modeling using R Language: theory and practice"
subtitle: Maurício Humberto Vancine, João Gabriel Ribeiro Giovanelli
draft: false
event: "9º CBH – IX Congresso Brasileiro de Herpetologia"
event_url: https://9cbh.galoa.com.br/en/inclusive-herpetology/
location: Campinas, SP, Brazil
summary: "Introduction to Species Distribution Models (SDMs) carried out in IX Congresso Brasileiro de Herpetologia"

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2019-07-22T08:00:00Z"
date_end: "2019-07-22T16:00:00Z"
all_day: false
publishdate: "2020-03-07"

links:
- icon: link
  icon_pack: fas
  name: event
  url: "https://9cbh.galoa.com.br/en/inclusive-herpetology/"  
- icon: github
  icon_pack: fab
  name: material
  url: "https://github.com/mauriciovancine/r-minicurso-sdm-9-cbh"

categories:
  - workshop
tags:
  - workshop
  - species distribution modelling
  - r
lastmod: r`Sys.Date()`
featured: no
image:
  caption: "[Imagem by Galoá](https://9cbh.galoa.com.br/)"
  focal_point: "center"
  preview_only: no
projects: []
---

The wide availability of data on biodiversity and environmental variables, has allowed the use of several biogeographic and macroecological analyzes, among them, the species distribution models (MDE). This short course aims to offer a theoretical and practical introduction to the EAW technique, using the R language. First, the main concepts of ecological niche theory (Grinnell, Elton and Hutchinson) and model theory (geographic space (G) , environmental space (E) and Biotic-Abiotic-Movement diagram (BAM)). Following the theoretical part, the main databases (occurrences and environmental variables), types of algorithms (presence and absence - GLM, GAM and Random Forest, only presence - BIOCLIM, Mahalanobis and Gower, and presence and background - Maxent and SVM), model evaluation (ROC, AUC and TSS), thresholds and some model consensus approaches (ensembles). The practical part will be focused on building models using the R language. Initially, an introduction to the programming and handling of spatial data in the R language will be made, using the *raster* and *rgdal* packages. Then, it will be presented how to obtain data of occurrences and environmental variables, through *spocc* and *dismo* packages. Once the data is acquired, preliminary analyzes will be made, such as selection of occurrences (one point per cell) and variables (correlation, PCA, factor analysis and VIF). Finally, models will be built using the algorithms mentioned above, in addition to calculating the evaluation metrics, using the *dismo*, *randomForest* and *kernlab* packages.
